# Assignment 2

# Section A (Data Structures & Control Structures)

In [ ]:
## Q1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
# Create a list of 5 integers
numbers = [10, 20, 30, 40, 50]
print("Original list:", numbers)

# 1. append()
numbers.append(60)
print("After append(60):", numbers)

# 2. extend() 
numbers.extend([70, 80])
print("After extend([70, 80]):", numbers)

# 3. insert() 
numbers.insert(2, 25)
print("After insert(2, 25):", numbers)

# 4. remove() 
numbers.remove(40)
print("After remove(40):", numbers)

# 5. pop() 
popped_value = numbers.pop()   # removes the last item
print("After pop():", numbers)
print("Popped value:", popped_value)

# 6. clear() 
numbers_copy = numbers.copy()  # copy before clearing for next operations
numbers.clear()
print("After clear():", numbers)

# Restoring from copy for next operations
numbers = numbers_copy

# 7. index() 
index_of_25 = numbers.index(25)
print("Index of 25:", index_of_25)

# 8. count() 
count_of_20 = numbers.count(20)
print("Count of 20:", count_of_20)

# 9. sort() 
numbers.sort()
print("After sort():", numbers)

# 10. reverse() 
numbers.reverse()
print("After reverse():", numbers)


Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(2, 25): [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove(40): [10, 20, 25, 30, 50, 60, 70, 80]
After pop(): [10, 20, 25, 30, 50, 60, 70]
Popped value: 80
After clear(): []
Index of 25: 2
Count of 20: 1
After sort(): [10, 20, 25, 30, 50, 60, 70]
After reverse(): [70, 60, 50, 30, 25, 20, 10]


In [ ]:
#Q2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
# Creating tuple with 3 student names
students = ("Alice", "Bob", "Charlie")
print("Original tuple:", students)

# changing the second name
students[1] = "David"   

#error
# reason for error is
# Tuples are immutable, you can’t change their elements directly.
# Lists are mutable, you can modify them freely.
# Tuples are immutable in Python, meaning once a tuple is created, its elements cannot be changed, added, or removed.


Original tuple: ('Alice', 'Bob', 'Charlie')


TypeError: 'tuple' object does not support item assignment

In [ ]:
# Q3. 3.	Create a set of integers with some duplicate values. Print the set and explain the output.
# Create a set with some duplicate integers
numbers = {10, 20, 30, 20, 40, 10, 50}

# Print the set
print("Set of numbers:", numbers)

#Sets automatically remove duplicates
# Even though 10 and 20 were repeated, they appear only once in the final set.
# it only keeps unique values
# Sets are unordered collections
# The elements don’t maintain the same order as you entered.
# Python may display them in any random order.



Set of numbers: {50, 20, 40, 10, 30}


In [1]:
# Q4. Create a dictionary with the keys: 'name', 'age', and 'city'. 
# Update the age and add a new key 'email'. Print the final dictionary.

# Create the dictionary
person = {'name': 'preetam', 'age': 25, 'city': 'banglore'}

# Update the age
person['age'] = 26

# Add a new key 'email'
person['email'] = 'preetam07 @example.com'

# Print the final dictionary
print("Final dictionary:", person)

# Explanation:
# Dictionaries store data as key-value pairs.
# The value of an existing key can be updated directly using the key name.
# A new key-value pair can be added by assigning a value to a new key.
# The final dictionary contains the updated 'age' and the new key 'email'.


Final dictionary: {'name': 'preetam', 'age': 26, 'city': 'banglore', 'email': 'preetam07 @example.com'}


In [7]:
# Q5. Write a script that checks if a person is eligible to vote (age ≥ 18). 
# Take age as a variable and print the appropriate message.

# Take age as a variable
age = int(input("Enter your age: "))

# Check voting eligibility
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

# Explanation:
# The input() function takes user input as a string, so we convert it to an integer using int().
# The if condition checks if the age is 18 or greater.
# If true, it prints that the person is eligible to vote.
# Otherwise, it prints that the person is not eligible yet.


You are eligible to vote.


In [8]:
# Q6. Given a 'marks' variable, print the grade:
# - 90 and above: 'A'
# - 75–89: 'B'
# - 50–74: 'C'
# - Below 50: 'Fail'

# Take marks as a variable
marks = int(input("Enter your marks: "))

# Check the grade based on marks
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")

# Explanation:
# The program checks the marks using if-elif-else conditions.
# - If marks are 90 or above, grade 'A' is printed.
# - If marks are between 75 and 89, grade 'B' is printed.
# - If marks are between 50 and 74, grade 'C' is printed.
# - If marks are below 50, 'Fail' is printed.


Grade: C


In [11]:
# Q7. Given a number, check if it's positive, and if it is also even. 
# If not positive, print if it's zero or negative.

# Take a number as input
num = int(input("Enter a number: "))

# Check conditions
if num > 0:
    if num % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

# Explanation:
# The program first checks if the number is positive, zero, or negative.
# - If positive, it further checks whether it’s even (divisible by 2) or odd.
# - If the number equals zero, it prints that it’s zero.
# - Otherwise, it prints that the number is negative.


The number is negative.


# Section B (Numpy)

In [ ]:
# Q8. Create different types of NumPy arrays
import numpy as np

# Scalar using np.array(5)
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", array_1d)

# 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("2D array (2x3):\n", array_2d)

# - scalar is a single value stored in a NumPy array.
# - array_1d is a one-dimensional array with 5 elements.
# - array_2d is a 2x3 two-dimensional array with values from 10 to 60.

Scalar: 5
1D array: [1 2 3 4 5]
2D array (2x3):
 [[10 20 30]
 [40 50 60]]


In [14]:
# Q9. Generate a 4x4 Numpy array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))
print("4x4 Random integers array:\n", random_array)


4x4 Random integers array:
 [[10 51  1 58]
 [93 50 13 95]
 [ 4 87 42 28]
 [27 17 23 24]]


In [15]:
# Q10. Create a 2D numpy array (3x3) and convert to pandas DataFrame with column names
import pandas as pd

# Create 2D array
array_2d_df = np.array([[1,2,3], [4,5,6], [7,8,9]])

# Convert to DataFrame and add column names
df = pd.DataFrame(array_2d_df, columns=['A', 'B', 'C'])
print("Pandas DataFrame:\n", df)

Pandas DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


# Section C (Exploring Pandas)

In [ ]:
# Q11. Create a small DataFrame manually with Indian names and cities, then perform operations
import pandas as pd
import numpy as np

# Create DataFrame manually
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Rohit', 'Anjali', 'Vikram', 'Neha', 'Karan', 'Simran'],
    'Age': [25, 30, 22, 28, 35, 40, 27, 29, 31, 25],
    'City': ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Jaipur', 'Lucknow', 'Ahmedabad'],
    'Salary': [50000, 60000, 55000, np.nan, 70000, 80000, 65000, 62000, 58000, np.nan]
}

df = pd.DataFrame(data)

# 1. Display information about the DataFrame
print("DataFrame info:")
print(df.info())
print("\nDataFrame description:")
print(df.describe())

# 2. Select 'Name' and 'City' columns
print("\nSelected columns ('Name' and 'City'):")
print(df[['Name', 'City']])

# 3. Drop 'City' column
df_dropped = df.drop('City', axis=1)
print("\nDataFrame after dropping 'City' column:")
print(df_dropped)

# 4. Fill missing values in 'Salary' with mean
salary_mean = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(salary_mean)
print("\nDataFrame after filling missing Salary values with mean:")
print(df)

# 5. Remove any duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nDataFrame after removing duplicates:")
print(df_no_duplicates)

DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

DataFrame description:
             Age       Salary
count  10.000000      8.00000
mean   29.200000  62500.00000
std     5.245104   9319.71796
min    22.000000  50000.00000
25%    25.500000  57250.00000
50%    28.500000  61000.00000
75%    30.750000  66250.00000
max    40.000000  80000.00000

Selected columns ('Name' and 'City'):
     Name       City
0    Amit     Mumbai
1   Priya      Delhi
2   Rahul  Bangalore
3   Sneha    Chennai
4   Rohit    Kolkata
5  Anjali  Hyderabad
6  Vikram       Pune
7    Neha     Jaipur
8   Karan    Lucknow
9  Simran  Ahmedabad

DataFrame after dropping